name:                SimpleMNIST
version:             0.1.0.0
github:              "sawatani/SimpleMNIST"
license:             BSD3
author:              沢谷 邦夫
maintainer:          hopstep@sawatani.jp
copyright:           "2019 fathens"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/SimpleMNIST#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  SimpleMNIST-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleMNIST

tests:
  SimpleMNIST-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleMNIST
