name:                SimpleMNIST
version:             0.2.0.0
github:              "sawatani/simple_mnist"
license:             BSD3
author:              沢谷 邦夫
maintainer:          hopstep@sawatani.jp
copyright:           "2019 fathens"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/sawatani/simple_mnist#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bifunctors
- bytestring
- cassava
- conduit
- containers
- deepseq
- directory
- extra
- filepath
- foundation
- hmatrix
- http-client
- http-types
- lens
- sort
- split
- string-interpolate
- time
- text
- transformers
- utf8-string
- mtl
- mwc-random
- regex
- yaml
- vector
- zlib

library:
  source-dirs: src

default-extensions:
- OverloadedStrings      

executables:
  SimpleMNIST-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleMNIST

tests:
  SimpleMNIST-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleMNIST
    - hspec
    - QuickCheck
